name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build App (No Archive)
        run: |
          xcodebuild \
          -scheme "Stable Action" \
          -configuration Release \
          -sdk iphoneos \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          build

      - name: Find App
        run: |
          mkdir Payload
          APP_PATH=$(find ~/Library/Developer/Xcode/DerivedData -name "*.app" | head -n 1)
          cp -r "$APP_PATH" Payload/

      - name: Create IPA
        run: zip -r StableAction.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: StableAction-IPA
          path: StableAction.ipa
