name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Archive
        run: |
          xcodebuild \
          -scheme "Stable Action" \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/StableAction.xcarchive \
          archive

      - name: Export IPA
        run: |
          mkdir -p build/ipa
          xcodebuild -exportArchive \
          -archivePath build/StableAction.xcarchive \
          -exportPath build/ipa \
          -exportOptionsPlist ExportOptions.plist || true

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: IPA
          path: build
