name: Build iOS IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Show Project Info
        run: |
          echo "Listing files..."
          ls
          echo "Searching Xcode projects..."
          find . -name "*.xcodeproj"
          find . -name "*.xcworkspace"

      - name: List Schemes
        run: xcodebuild -list
