name: Build IPA

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build Archive (No Signing)
        run: |
          xcodebuild \
          -scheme "Stable Action" \
          -configuration Release \
          -sdk iphoneos \
          CODE_SIGNING_ALLOWED=NO \
          CODE_SIGNING_REQUIRED=NO \
          -archivePath build/StableAction.xcarchive \
          archive

      - name: Create IPA
        run: |
          mkdir Payload
          cp -r build/StableAction.xcarchive/Products/Applications/*.app Payload/
          zip -r StableAction.ipa Payload

      - name: Upload IPA
        uses: actions/upload-artifact@v4
        with:
          name: StableAction-IPA
          path: StableAction.ipa
